name: Build and Run Game

on:
  workflow_run:
    workflows: ["Run Smoke Test"]
    types:
      - completed
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-run:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Odin
      uses: laytan/setup-odin@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile Odin vendor libraries
      run: |
        cd $(odin root)/vendor/stb/src && make
        cd $(odin root)/vendor/cgltf && make

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.4.309.0
        vulkan-use-cache: true

    - name: Install Xvfb for headless display
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Build the game
      run: make build

    - name: Run the game for 10 seconds
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &
        timeout --preserve-status 10s ./mjolnir || true
        echo "Game ran successfully for 10 seconds"
